version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: atende-ai-backend:latest
    container_name: atende-ai-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - vps2net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atende-ai-api.rule=Host(`api.lionchat.tech`)"
      - "traefik.http.routers.atende-ai-api.entrypoints=websecure"
      - "traefik.http.routers.atende-ai-api.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.atende-ai-api.loadbalancer.server.port=3000"
      - "traefik.docker.network=vps2net"

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: atende-ai-backend:latest # Reutiliza a mesma imagem do backend
    container_name: atende-ai-worker
    command: ["npm", "run", "start:worker"]
    restart: unless-stopped
    env_file:
      - ./backend/.env
    networks:
      - vps2net

networks:
  vps2net:
    external: true
