[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile" 

[deploy]
healthcheckPath = "/health" # ou "/api/health" se for isso mesmo no backend
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
